### ISSUE TITLE
Failing builds on github actions with development version of mlr3

### ISSUE THREAD

**Issue by PhilippBach** [DoubleML/doubleml-for-r#145]
https://github.com/DoubleML/doubleml-for-r/actions/runs/1657577777

I have to check why the build fails, seems to be related to markdown / vignettes

**Comment by MalteKurz** [comment]
Saw this also. It fails in the following lines of the "Getting Started" guide
https://github.com/DoubleML/doubleml-for-r/blob/4e5c45a7f1e49e8383cbc6798783b6914dec88ad/vignettes/getstarted.Rmd#L124-L132
So guess you just have to run it with the dev version of `mlr3` to get more insights.

**Comment by PhilippBach** [comment]
Seems that it works again. 

https://github.com/DoubleML/doubleml-for-r/actions/runs/1720147301
