### ISSUE TITLE
Inconsistent initilization of `task_type` between PLIV and other models (PLR, IRM, IIVM)

### ISSUE THREAD

**Issue by MalteKurz** [DoubleML/doubleml-for-r#157]
## PLR, IRM and IIVM
For PLR, IRM and IIVM, we first initialize the private property `task_type` to `NULL` for all necessary nuisance parts and during the call to `assert_learner` it is filled up with content. See
https://github.com/DoubleML/doubleml-for-r/blob/acb9d46ee7eece72efff61e6cdc089c69696572b/R/double_ml_plr.R#L150-L154
https://github.com/DoubleML/doubleml-for-r/blob/acb9d46ee7eece72efff61e6cdc089c69696572b/R/double_ml_irm.R#L192-L196
https://github.com/DoubleML/doubleml-for-r/blob/acb9d46ee7eece72efff61e6cdc089c69696572b/R/double_ml_iivm.R#L248-L254

## PLIV
For PLIV this initialization does not happen, but still it seems to work as expected, see

https://github.com/DoubleML/doubleml-for-r/blob/acb9d46ee7eece72efff61e6cdc089c69696572b/R/double_ml_pliv.R#L208-L216

## Possible solution

In the base class `DoubleML` the private property `task_type` is initialized to an empty list, which in my view suffices. 
https://github.com/DoubleML/doubleml-for-r/blob/acb9d46ee7eece72efff61e6cdc089c69696572b/R/double_ml.R#L1153
It is then filled up with meaningful content when `assert_learner` is being called for the learners assigned for the different nuisance parts. Therefore, I guess we could simplify by removing the additional nuisance-part specific initialization to `NULL` being done for PLR, IRM and IIVM.

## Miscellaneous
I would furthermore would suggest to add some sort of assertion in the helper function `dml_cv_predict`. Basically, I wouldn't accept something else than `"regr"` or `"classif"`. The code will anyways fail with any other choice, like `NULL`, because then variable `resp_name` would never be assigned, see
https://github.com/DoubleML/doubleml-for-r/blob/acb9d46ee7eece72efff61e6cdc089c69696572b/R/helper.R#L162-L166

**Comment by PhilippBach** [comment]
Hi @MalteKurz , 

sorry for my late reply again. Thanks for proposing the changes! I think this makes sense. Looks good!
