### ISSUE TITLE
Heads up: Upcoming "paradox" CRAN release will break DoubleML

### ISSUE THREAD

**Issue by mb706** [DoubleML/doubleml-for-r#194]
We are in the process of overhauling the `paradox` package, on which DoubleML depends: On 2024-06-10 (or earlier, if our reverse dependencies are fixed before this :-) ), we are going to put https://github.com/mlr-org/paradox on CRAN.

This will remove the `ParamDbl`, `ParamInt` etc. classes, instead only the `ParamSet` class will remain, representing the parameter space as a table. Constructing a `ParamSet` will then need to be done using the shorthand forms `ps()`, `p_dbl()`, `p_int()` etc. See [this diff](https://github.com/mlr-org/mlr3pipelines/pull/752/files#diff-bccd0d30e65d0fece49968c6735dd5e0c7974e8f8b4589e1168cf421555729aa) of `PipeOpImputeOOR.R` in `mlr3pipelines` as an example of what changes are necessary.

Note that `ps()`, `p_dbl()` etc. is already possible (and the recommended way of doing this!), we are just phasing out the old `ParamDbl$new()` way.

I will prepare a PR shortly that hopefully fixes most of this.

**Comment by PhilippBach** [comment]
Thanks for the heads up! Looking forward for the PR! Thanks for your efforts for `paradox`

**Comment by PhilippBach** [comment]
Hi @mb706 , 

thanks for opening the pull requests. I think so far it looks good. 

Before we merge the PR, I'd have to do some minor adjustments to our docs: https://github.com/DoubleML/doubleml-docs/issues/170

I think that should be done by the end of this week. We'll issue a CRAN release ASAP.

Thanks!

Philipp

**Comment by PhilippBach** [comment]
Hi @mb706 , 

thanks again for the heads up and the preparation for the PR. I just wanted to give you a little update: Yesterday we triggered the CRAN release of the updated version. Once DoubleML 1.0.1 is on CRAN, I'll send you a brief update and close this issu. 

Thanks!

**Comment by PhilippBach** [comment]
Hi @mb706 ,

just to complete this. The fixed version of DoubleML 1.0.1 is now available at CRAN and we also updated all related files in the docu. 

Thanks and best, 

Philipp
