### ISSUE TITLE
mlr3tuning API change

### ISSUE THREAD

**Issue by be-marc** [DoubleML/doubleml-for-r#51]
We will upload a new version of `mlr3tuning` to CRAN. 
This line will no longer work.
https://github.com/DoubleML/doubleml-for-r/blob/9b30b4289d40a7f02d68f3c2d1a04ce8364cfd49/R/helper.R#L132

You have to use `tuning_instance$archive$data` since the data table is now accessible via a public field instead by a function.

**Comment by MalteKurz** [comment]
* Thanks for the heads up @be-marc :+1:.
* I checked your repo. I assume you plan to submit version 0.6.0?
* We will adapt accordingly. Test it vs. your dev version from https://github.com/mlr-org/mlr3tuning and then also publish a minor release to CRAN with the fix.
